const iconModules = import.meta.glob("../../assets/icons/*.svg", {
    eager: true,
    query: "?url",
    import: "default",
});

const getIconUrl = (fileName) => iconModules[`../../assets/icons/${fileName}.svg`];

export const ICON = {
    search: getIconUrl("search"),
    clear: getIconUrl("delete"),
    down: getIconUrl("arrow_down"),
    arrowRight: getIconUrl("arrow_right"),
    chk: getIconUrl("chk"),
    unchk: getIconUrl("unchk"),
    dis_unchk: getIconUrl("dis_unchk"),
    dis_chk: getIconUrl("dis_chk"),
    chk_rad: getIconUrl("chk_rad"),
    unchk_rad: getIconUrl("unchk_rad"),
    dis_unchk_rad: getIconUrl("dis_unchk_rad"),
    dis_chk_rad: getIconUrl("dis_chk_rad"),
    chkbx: getIconUrl("chkbx"),
    unChkbx: getIconUrl("un_chkbx"),
    dis_unChkbx: getIconUrl("dis_unchkbx"),
    dis_chkbx: getIconUrl("dis_chkbx"),
    upload: getIconUrl("upload"),
    dis_upload: getIconUrl("dis_upload"),
    refresh: getIconUrl("refresh"),
    dis_refresh: getIconUrl("dis_refresh"),
    calendar: getIconUrl("calendar"),
    time: getIconUrl("time"),
    spinnerTime: getIconUrl("spinner_time"),
    step1: getIconUrl("step_error"),
    step2: getIconUrl("step_done"),
    step3: getIconUrl("step_ongoing"),
    step4: getIconUrl("step_wait"),
    alert1: getIconUrl("info"),
    menu_group: getIconUrl("menu_group"),
    logout: getIconUrl("logout"),
    bookmark: getIconUrl("bookmark"),
    info: getIconUrl("info"),
    tableinfo: getIconUrl("info_table"),
    home: getIconUrl("home"),
    no_data: getIconUrl("no_data"),
    voice: getIconUrl("voice"),
    play: getIconUrl("play"),
    edit: getIconUrl("edit"),
    prev_page: getIconUrl("prev_page"),
    next_page: getIconUrl("next_page"),
    first_page: getIconUrl("first_page"),
    last_page: getIconUrl("last_page"),
    pop_close: getIconUrl("pop_close"),
    sidemenu1: getIconUrl("sidemenu1"),
    sidemenu2: getIconUrl("sidemenu2"),
    sidemenu3: getIconUrl("sidemenu3"),
    sidemenu4: getIconUrl("sidemenu4"),
    sidemenu5: getIconUrl("sidemenu5"),
    sidemenu6: getIconUrl("sidemenu6"),
    sidemenu7: getIconUrl("sidemenu7"),
    sidemenu8: getIconUrl("sidemenu8"),
};
